# Generated by Django 5.0.6 on 2024-05-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=90)),
                ('contrasena', models.CharField(max_length=90)),
                ('usuario', models.CharField(max_length=90)),
                ('rol', models.CharField(max_length=90)),
            ],
        ),
    ]
