# Generated by Django 5.0.6 on 2024-05-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_cafe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
