# Generated by Django 5.0.4 on 2024-05-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0002_producto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
