# Generated by Django 5.0.6 on 2024-06-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0006_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nombre_cliente',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
